const answers = [
  "You’re going to hell, don’t even try.",
  "The answers you seek are beyond your grasp.",
  "You’re destined for chaos, accept it.",
  "Maybe the answer is to stop asking.",
  "Your questions are a cosmic joke, enjoy the punchline.",
  "The divine is laughing at your confusion.",
  "Every question leads to more confusion, deal with it.",
  "The universe has better things to do than answer you.",
  "You’re on a path to nowhere, enjoy the ride.",
  "The answer is not what you want to hear.",
  "You might as well ask a brick wall.",
  "Your fate is written in chaos, embrace it.",
  "The answers are hidden behind a veil of confusion.",
  "You’re lost in the cosmic shuffle.",
  "Even the divine is baffled by your questions.",
  "You’re destined for a life of unanswered queries.",
  "The answers are out of your reach, and they’re laughing.",
  "Maybe you should try asking a different deity.",
  "Your journey is a quest for nothing, enjoy the trip.",
  "The cosmic winds blow against you.",
  "You’re swimming in a sea of confusion.",
  "The divine’s not interested in your problems today.",
  "Your questions are leading to more questions, not answers.",
  "The universe is indifferent to your plight.",
  "You’re on your own with this one.",
  "The stars have better things to do than guide you.",
  "Your path is a labyrinth with no exit.",
  "Even I can’t help you with this mess.",
  "You’re chasing shadows in the cosmic void.",
  "The answer is as elusive as a mirage.",
  "Your fate is a series of unfortunate events.",
  "Maybe the real answer is to stop asking.",
  "The divine has checked out on this one.",
  "You’re caught in a web of your own making.",
  "Your quest for answers is a wild goose chase.",
  "The cosmic joke is on you.",
  "You’re out of luck with this question.",
  "Even gods need a break from your inquiries.",
  "The universe is not amused by your persistence.",
  "Your answers are in the land of ‘maybe’.",
  "You’re adrift in the sea of uncertainty.",
  "The divine’s patience has run out.",
  "Your questions are too convoluted to answer.",
  "The stars are laughing at your confusion.",
  "You’re in for a rough ride, cosmic style.",
  "The answer is to accept that there is none.",
  "You’re on a wild ride with no destination.",
  "The cosmic winds are against you today.",
  "Your fate is to search endlessly for clarity.",
  "The universe is playing a trick on you.",
  "Even the divine is shaking its head.",
  "You’re caught in the cosmic crossfire.",
  "The stars have turned their back on you.",
  "The divine has left the building.",
  "You’re stuck in a cosmic loop of confusion.",
  "Your quest for answers is a cosmic dead end.",
  "The answer is beyond your comprehension.",
  "You’re in the midst of a divine prank.",
  "The cosmic winds are howling against you.",
  "You’re on your own with this cosmic riddle.",
  "Even gods can’t untangle this mess.",
  "Your fate is sealed in confusion.",
  "The divine is enjoying your perplexity.",
  "You’re lost in a maze with no exit.",
  "The universe has given up on your questions.",
  "You’re chasing illusions in the cosmic haze.",
  "The stars have aligned against you.",
  "The answer is lost in the void of space.",
  "You’re out of luck with this cosmic query.",
  "The divine is taking a vacation from you.",
  "You’re adrift in a sea of cosmic chaos.",
];

console.log(answers);
